language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- BOARD=uno
- BOARD=leonardo
- BOARD=megaatmega2560
- BOARD=due
- BOARD=genuino101
- BOARD=zero

script:
- for e in examples/*; do
    platformio ci --board=$BOARD --lib=. $e/*;
  done

notifications:
  flowdock:
    # main flow
    - secure: "s5rnkMOHthYGfKZGDrgdQsdYAEstP6VJHS36DKDUFnso+JnXrOH9kUAfhReh7xPMuKBIKddhiGtXnZz7zQXbEMf4x93qS4/RU81V8vs1rMYR4WN0UCorETQxfC5jNQkJUXhcdFqwKQXejSSAeimwQMhGtCBIQ1qmam8ObvumA+1leRHuclJZVZCzNwRGId6obbjFzVpJB13H8aZLe4Uj4YSCyJoB29NgBuPnGDxTE+4p5IBnlEcI4DlU46gI2i2CmTRuqmAqKOMkyC4ZJa2VcZtbk+OzVhznTJIHGy+blFfUHpXEKeKcItmgT5ZfUxguUM1Ow6NntRG2z0qqUWAK9a4XxC1Ax8wmGBkfjGEc0UA2cSpuEzxeUMg0XC2bpEoh5I8BsQJ12wujQ4MzRXJBT2LDpiK1QRKx9s9z9cqDSxnRNX6FdJ3Je9KR8XuZdWTiJZgx4DYFO1i0lPEE48aFVoGq+F1357L505WUuDnKA8F3IU9aqXH9MJW37xAY0wDerqB8qxiROuk1y/ek9VKdThaFtV31l6E4/XMCpKHJscXGIMQWLyK+x4fxbYkH9vlXJiZPrLUzdxgXhLd13k5mj0JEcOfs/TU8Z45nlpVL3L7htR/Z7iy5GLGbrjg9EUtJGstL+PLjreV9dh1aPs5DTeYwjNq5iQ7EIacXt7EtyWI="
    # software team
    - secure: "V59sJjaSL5EJJOPpJvJsjbnEdHDaBwvYxfF3YyTOMcA+V3Tm8eLe6pPaYfLkyxFXUCsObEiLl7szo+dGo8U2f82burn+oYyffzZD4QNH4xoKts/WwquBi9n6/qytCVgaQjGPHlqMbncHTXno7JTYktvXgSleqyiiPZJEZdUrHd4ipFt7BbBClLEsWOpachBeaVzFP66arHuHr+v21Kxg5svyNr67k9exgyucYu3KhYpIKdjGV33GZRqw4yajit86j/EKQyI98D4fuVKE4Gww6WVzi4mIOMPSVsGD1YU1rbqFUVqvy5x1UoUomvdkrHlyodlyLKVS8T9VzrcXVbllyxvxT+I02iaee+uiyC2Ke6jUveviRfiYBRozXL7Ks2AfY1PU+2NHZXRkcqzOgPYHfdoDcBkScPoc86+rmedVYdyOg2bsq51S3HtlVtd4069gvnSe4XA//2rgS/Fr5cQwQZCib/e4Bhp39taMYLIqewssQKYpOaSIhwRx+Hsj5UkHWe0xjRJ48W3g8/RWgqFOcgcVv9BeGUeIPbu8WltHSB6AcT7Ce+nLBFFm2uhdx6vUzQEN5KQPJF8pjaX0K26b0PLEtHQZ62GkKscai+whz9FykcA/Uc0kzZm2lAnDe13dF1H87Qz6VlTfFeZd3GLLw7JpnJYJBwlWS6TtUNED+p4="
